app/groups/models.py
from peewee import Model, CharField, ForeignKeyField
from app.init_db import database
#from app.students.models import Stud

from .proxy import StudProxy


class Group(database.Model):
    name = CharField(verbose_name="Наименование", max_length=16, unique=True)
    starosta = ForeignKeyField(StudProxy, null=True, verbose_name="Староста")

    def __str__(self):
        return self.name

app/groups/views.py
from wtfpeewee.orm import model_form
from flask import g, Blueprint
from flask import render_template, redirect, url_for, request

from app.universal import get_object_or_404
from app.accounts.session import login_required
from app.students.models import Stud
from .models import Group

bp = Blueprint('group', __name__, template_folder='templates')

@bp.route('/')
def groups_list():
    glist = Group.select().order_by(Group.name)
    #context = ['groups_list'=glist]
    template_name = 'groups/groups_list.html'
    return render_template(template_name, groups_list=glist)

@bp.route('/<group_id>/')
def studs_list(group_id):
    group = get_object_or_404(Group, Group.id == group_id)
    template_name = 'groups/studs_list.html'
    return render_template(template_name, group=group)

@bp.route('/create/', methods=['GET', 'POST'])
@login_required
def group_create():
    GroupForm = model_form(Group)
    group = Group()
    if request.method == 'POST':
        form = GroupForm(request.form, obj=group)
        if form.validate():
            form.populate_obj(group)
            group.save()
            return redirect(url_for('group.groups_list'))
    else:
        form = GroupForm(obj=group)
    return render_template('groups/group_form.html', form=form)

@bp.route('/<group_id>/edit/', methods=['GET', 'POST'])
@login_required
def group_edit(group_id):
    GroupForm = model_form(Group)
    group = get_object_or_404(Group, Group.id == group_id)
    if request.method == 'POST':
        form = GroupForm(request.form, obj=group)
        if form.validate():
            form.populate_obj(group)
            group.save()
            return redirect(url_for('group.groups_list'))
    else:
        form = GroupForm(obj=group)
        form.starosta.query = Stud.filter(cgroup=group)
    return render_template('groups/group_form.html', form=form, group=group)

@bp.route('/<group_id>/delete/', methods=['POST'])
@login_required
def group_delete(group_id):
    group = get_object_or_404(Group, Group.id == group_id)
    try:
        group.delete_instance()
        return redirect(url_for('group.groups_list'))
    except Exception as e:
        return redirect(url_for('group.group_edit', group_id=group_id))

@bp.route('/<group_id>/confirm_delete', methods=['POST'])
@login_required
def confirm_delete(group_id):
    group = get_object_or_404(Group, Group.id == group_id)
    template_name = 'groups/confirm_delete.html'
    return render_template(template_name, group=group)

app/groups/templates/groups/confirm_delete.html
{% extends "groups/studs_list.html" %}

{% block header %}В группе {{ group.name }}, которую Вы хотите удалить, обучаются студенты{% endblock %}

{% block another %}
        <form method="post" action="{{ url_for('group.group_delete', group_id=group.id) }}" class="text-right">
            <input type="submit" value="Все равно удалить эту группу" class="btn btn-default">
        </form>
{% endblock another %}

app/groups/templates/groups/group_form.html
{% extends "base.html" %}


{% block header %}{% if group %}Группа {{ group.name }}{% else %}Создание новой группы{% endif %}{% endblock %}

{% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="." method="post" class="form-horizontal">
            {{ form.csrf_token }}
            {% for field in form %}
              {% if group or (field.name != 'starosta') %}
              <div class="form-group{% if field.errors %} has-error{% endif %}">
                {{ field.label(class="control-label") }}
                {{ field(class="form-control") }}
                {% if field.errors %}
                  <ul class="list-unstyled">
                  {% for error in field.errors %}
                    <li class="text-danger">{{ error|e }}</li>
                  {% endfor %}
                  </ul>
                {% endif %}
              </div>
              {% endif %}
            {% endfor %}
            <div class="col-sm-2">
                <input type="submit" value="Сохранить" class="btn btn-primary">
            </div>
        </form>
        {% if group %}
        <form class="col-sm-2" method="post" action="{% if group.stud_set.count() > 0 %}{{ url_for('group.confirm_delete', group_id=group.id) }}{% else %}{{ url_for('group.group_delete', group_id=group.id) }}{% endif %}">
            {{ form.csrf_token }}
            <input type="submit" class="btn btn-default" onclick="{% if group.stud_set.count() == 0 %}return confirm('Удалить группу {{ group.name }}?'){% endif %}"  value="Удалить группу">
        </form>
        {% endif %}
{% endblock content %}

            

app/groups/templates/groups/groups_list.html
{% extends "base.html" %}

{% block header %}Список Групп{% endblock %}

{% block content %}
{% if groups_list %}
        <table class="table table-striped" id="studs">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Наименование</th>
                    <th>Староста</th>
                    <th class="text-center">Кол-во человек</th>
                    <th class="text-center">Действие</th>
                <tr>
            </thead>
            <tbody class="table_body">
            {% for group in groups_list %}
                <tr>
                    <td>{{ group.id }}</td>
                    <td><a href="{{ url_for('group.studs_list', group_id=group.id) }}">{{ group.name }}</a></td>
                    <td>{% if group.starosta %}{{ group.starosta }}{% endif %}</td>
                    <td class="text-center">{{ group.stud_set.count() }}</td>
                    <td class="text-center"><a href="{{ url_for('group.group_edit', group_id=group.id) }}">Edit</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% else %}
    <p>No groups are avaliable</p>
{% endif %}

        <form method="LINK" action="{{ url_for('group.group_create') }}" class="text-right">
            <input type="submit" value="Создать" class="btn btn-default">
        </form>

{% endblock content %}

app/groups/templates/groups/studs_list.html
{% extends "base.html" %}

{% block header %}Список студентов группы {{ group.name }}{% endblock %}

{% block content %}
{% if group.stud_set.count() > 0  %}
        <table class="table table-striped" id="studs">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>ФИО</th>
                    <th>Дата рождения</th>
                    <th>№ студ-билета</th>
                    <th class="text-center">Cтароста</th>
                <tr>
            </thead>
            <tbody class="table_body">
            {% for stud in group.stud_set %}
                <tr>
                    <td>{{ stud.id }}</td>
                    <td><a href="{{ url_for('stud.stud_edit', stud_id=stud.id, group_id=group.id)  }}">{{ stud.name }}</a></td>
                    <td>{{ stud.dbirthday.strftime('%d.%m.%Y') }}</td>
                    <td>{{ stud.nstud }}</td>
                    <td class="text-center"><input type="checkbox" disabled {% if stud == group.starosta %}checked{% endif %}></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <hr>
        <p class="text-right"><strong>Всего студентов: {{ group.stud_set.count() }}</strong></p>
{% else %}
    <p class="text-center text-warning">No students are avaliable</p>
{% endif %}
{% block another %}
        <form method="LINK" action="{{ url_for('stud.stud_create', group_id=group.id) }}" class="text-right">
            <input type="submit" value="Создать" class="btn btn-default">
        </form>
{% endblock another %}
{% endblock content %}