app/students/models.py
from peewee import Model, CharField, DateField, ForeignKeyField
from app.init_db import database

from app.groups.models import Group
from app.groups.proxy import StudProxy


class Stud(database.Model):
    name = CharField(verbose_name="ФИО", max_length=128)
    dbirthday = DateField(verbose_name="Дата рождения")
    nstud = CharField(verbose_name="Студенческий билет", max_length=15, unique=True)
    cgroup = ForeignKeyField(Group, verbose_name="Группа")

    def __str__(self):
        return self.name

StudProxy.initialize(Stud)

app/students/views.py
from wtfpeewee.orm import model_form
from flask import Blueprint
from flask import render_template, redirect, request, url_for

from app.universal import get_object_or_404
from app.accounts.session import login_required
from app.groups.models import Group
from .models import Stud

bp = Blueprint('stud', __name__, template_folder='templates')

@bp.route('/<group_id>/create/', methods=['GET', 'POST'])
@login_required
def stud_create(group_id):
    StudForm = model_form(Stud)
    stud = Stud()
    if request.method == 'POST':
        form = StudForm(request.form)
        if form.validate():
            form.populate_obj(stud)
            stud.save()
            return redirect(url_for('group.studs_list', 
                                    group_id=group_id))
    else:
        stud.cgroup = get_object_or_404(Group, Group.id == group_id)
        form = StudForm(obj=stud)
    return render_template('students/stud_form.html', 
                            form=form, group_id=group_id)

@bp.route('/<stud_id>/edit/<group_id>/', methods=['GET', 'POST'])
@login_required
def stud_edit(stud_id, group_id):
    StudForm = model_form(Stud, field_args={'dbirthday': dict(format='%d.%m.%Y')})
    stud = get_object_or_404(Stud, Stud.id == stud_id)
    if request.method == 'POST':
        form = StudForm(request.form, obj=stud)
        if form.validate():
            form.populate_obj(stud)
            stud.save()
            return redirect(url_for('group.studs_list', 
                                    group_id=group_id))
    else:
        form = StudForm(obj=stud)
    return render_template('students/stud_form.html', 
                           form=form, stud=stud, group_id=group_id)

@bp.route('/<stud_id>/delete/<group_id>/', methods=['POST'])
@login_required
def stud_delete(stud_id, group_id):
    stud = get_object_or_404(Stud, Stud.id == stud_id)
    try:
        stud.delete_instance()
        return redirect(url_for('group.studs_list', 
                        group_id=group_id))
    except Exception as e:
        StudForm = model_form(Stud)
        form = StudForm(obj=stud)
        return render_template('students/stud_form.html', 
                     form=form, stud=stud, error_message=e)

app/students/templates/students/stud_form.html
{% extends "base.html" %}


{% block header %}{% if stud %}Студент {{ stud.name }}{% else %}Создание нового студента{% endif %}{% endblock %}

{% block add_links %}<li><a href="{{ url_for('group.studs_list', group_id=group_id) }}">Список студентов</a></li>{% endblock %}

{% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form class="form-horizontal" action="." method="post">
            {{ form.csrf_token }}
            {% for field in form %}
              <div class="form-group{% if field.errors %} has-error{% endif %}">
                {{ field.label(class="control-label") }}
                {{ field(class="form-control") }}
                {% if field.errors %}
                  <ul class="list-unstyled">
                  {% for error in field.errors %}
                    <li class="text-danger">{{ error|e }}</li>
                  {% endfor %}
                  </ul>
                {% endif %}
              </div>
            {% endfor %}
            <div class="col-sm-2">
                <input type="submit" value="Сохранить" class="btn btn-primary">
            </div>
        </form>
        {% if stud %}
        <form class="col-sm-2" action="{{ url_for('stud.stud_delete', stud_id=stud.id, group_id=stud.cgroup.id) }}" method="post">
            {{ form.csrf_token }}
            <input type="submit" class="btn btn-default" onclick="return confirm('Удалить студента {{ stud.name }}?')"  value="Удалить студента">
        </form>
        {% endif %}
{% endblock content %}