app/accounts/views.py
import datetime
from wtfpeewee.orm import model_form
from flask import g, Blueprint, session, flash
from flask import render_template, redirect, url_for, request
from hashlib import md5
from peewee import IntegrityError

from app.universal import get_object_or_404
from app.init_db import database
from .models import User
from .session import auth_user

bp = Blueprint('acc', __name__, template_folder='templates')

@bp.route('/join/', methods=['GET', 'POST'])
def join():
    if request.method == 'POST' and request.form['username']:
        try:
            with database.db.transaction():
                user = User.create(
                    username=request.form['username'],
                    password=md5((request.form['password']).encode('utf-8')).hexdigest(),
                    join_date = datetime.datetime.now())
            auth_user(user)
            return redirect(url_for('group.groups_list'))
        except IntegrityError:
            flash('Пользователь с таким именем уже существует')
    LoginForm = model_form(User, exclude=('join_date',))
    form = LoginForm()
    return render_template('acc/login.html', form=form)


@bp.route('/login/', methods=['GET', 'POST'])
def login():
    next_url = request.args.get('next') or request.form.get('next')
    LoginForm = model_form(User, exclude=('join_date',))
    form = LoginForm()
    if request.method == 'POST' and request.form['username']:
        try:
            user = User.get(
                username=request.form['username'],
                password=md5((request.form['password']).encode('utf-8')).hexdigest())
        except User.DoesNotExist:
            errors = "Неверное имя пользователя или пароль. Повторите попытку"
            return render_template('acc/login.html', form=form, next=next_url, error_message=errors)
        else:
            auth_user(user)
            return redirect(next_url) # or url_for('group.groups_list'))
    LoginForm = model_form(User, exclude=('join_date',))
    form = LoginForm()
    return render_template('acc/login.html', form=form, next=next_url)


@bp.route('/logout/')
def logout():
    session.pop('logged_in', None)
    return redirect(url_for('group.groups_list'))

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}" />
    <title>{% block title %}Управление базой студентов{% endblock %}</title>
    {% block script %}{% endblock %}
</head>

<body>{% block body %}
{% block scriptbody %}{% endblock scriptbody %}
    <div class = "row">
        <div class="col-md-3"></div>
        <div class="col-md-6 text-right">
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <div class="navbar-header">
                  <a class="navbar-brand" href="#">Управление базой студентов</a>
                </div>
                <div class="collapse navbar-collapse">
                  <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('group.groups_list') }}">Список групп</a></li>
                    {% block add_links %}{% endblock add_links %}
                  </ul>
                  {% block loginout %}
                  {% if session.logged_in %}
                  <p class="navbar-text navbar-right">Пользователь: {{ session.username }} <a class="navbar-link" href="{{ url_for('acc.logout') }}">Выход</a></p>
                  {% else %}
                  <ul class="nav navbar-nav navbar-right">
                    <li><a class="navbar-link" href="{{ url_for('acc.login') }}">Вход</a></li>
                  </ul>
                  {% endif %}
                  {% endblock loginout %}
                </div>
              </div>
            </nav>
        </div>
        <div class="col-md-3"></div>
    </div>
    <div class = "row">
        <div class="col-md-12">
            <header>
            <h1 class="text-center">{% block header %}Управление базой студентов{% endblock %}</h1>
            </header>
        </div>
    </div>
    <div class = "row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div id="content">
            {% block content %}{% endblock %}
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>

{% endblock body %}
</body>
</html>